theme: jekyll-theme-cayman
title: AutoSimGeo 
description: AI-driven Autonomous Simulations in Computational Geomechanics via Natural Language Instructions
markdown: kramdown
kramdown:
    math_engine: mathjax
    syntax_highlighter: rouge